
import { Inter } from 'next/font/google'
import './globals.css'
import * as React from "react";
import { Providers } from './providers';
import {Navbar, NavbarBrand, NavbarContent,NavbarMenuToggle, NavbarItem, Link, Button} from "@nextui-org/react";
import Header from './components/header/Header';


const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className='dark min-h-screen'>
        <body className="dark text-foreground bg-background min-h-screen flex flex-col">
          <Providers>
            <Header />
            <main className="w-full min-h-screen h-screen flex">
                {children}
              </main>
          </Providers>
        </body>
    </html>
  );
}
